name: Verify formatting

on:
  push:
    branches: 
        - master
        - 'test/*'
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    name: Verify Python formatting
    steps:
    - uses: actions/checkout@v4

    - uses: astral-sh/ruff-action@v3
      with:
        version: "0.11.2"
        args: "format --check"
